export const configurations = {
    hexagon: {
        width: 1000,
        height: 800,
        layout: { width: 8, height: 8, flat: false, spacing: 1.02 },
        origin: { x: 0, y: 0 },
        map: "hexagon",
        mapProps: [3],
    },
    triangle: {
        width: 1000,
        height: 800,
        layout: { width: 9, height: 9, flat: false, spacing: 1.05 },
        origin: { x: -45, y: -35 },
        map: "triangle",
        mapProps: [5],
    },
    parallelogram: {
        width: 1000,
        height: 800,
        layout: { width: 7, height: 7, flat: true, spacing: 1.05 },
        origin: { x: 0, y: 0 },
        map: "parallelogram",
        mapProps: [-2, 2, -2, 2],
    },
    rectangle: {
        width: 1000,
        height: 800,
        layout: { width: 6, height: 6, flat: false, spacing: 1.02 },
        origin: { x: -45, y: -40 },
        map: "rectangle",
        mapProps: [10, 10],
    },
    orientedRectangle: {
        width: 1000,
        height: 800,
        layout: { width: 6, height: 6, flat: false, spacing: 1.1 },
        origin: { x: -45, y: -15 },
        map: "orientedRectangle",
        mapProps: [7, 7],
    },
    ring: {
        width: 1000,
        height: 800,
        layout: { width: 6, height: 6, flat: false, spacing: 1.1 },
        origin: { x: 0, y: 0 },
        map: "ring",
        mapProps: [{ q: 0, r: 0, s: 0 }, 3],
    },
    spiral: {
        width: 1000,
        height: 800,
        layout: { width: 6, height: 6, flat: false, spacing: 1.1 },
        origin: { x: 0, y: 0 },
        map: "spiral",
        mapProps: [{ q: 0, r: 0, s: 0 }, 3],
    },
};
//# sourceMappingURL=configurations.js.map